### ISSUE TITLE
buildpack failures .. failed to compile Multipack app

### ISSUE THREAD

**Issue by prussiap** [rolandjitsu/heroku-buildpack-mosquitto#2]
Finally got followed everything you said but I get :

```
remote: -----> Installing openssl_1.0.1f-1ubuntu2.11_amd64.deb
remote: -----> Installing pkg-config_0.26-1ubuntu4_amd64.deb
remote: -----> Writing profile script
remote: =====> Downloading Buildpack: https://github.com/rolandjitsu/heroku-buildpack-mosquitto.git
remote:
remote:  !     Push rejected, failed to compile Multipack app
remote:
remote: Verifying deploy...
remote:
remote: !	Push rejected to radiant-headland-5685.
```

on push.. do i need to add package.json and Gemfile too ? what else could have changed?

**Comment by rolandjitsu** [comment]
@prussiap sorry for the late reply, busy at the office :) It looks like the [heroku-buildpack-multi](https://github.com/ddollar/heroku-buildpack-multi) is failing for some reason.

You might want to take a look at the [Heroku documentation on buildpacks](https://devcenter.heroku.com/articles/buildpacks) if you haven't already, It might be that you forgot something.

**P.S.** As a sidenote, `package.json` and `Gemfile` are two different things and not related to a buildpack. The `package.json` is a [npm](https://www.npmjs.com) specific project manifest file for apps that use [nodejs](http://nodejs.org), and the `Gemfile` is a manifest file used by [bundler](http://bundler.io) to install all the gems specified in that file (for apps that are built with Ruby).

**Comment by prussiap** [comment]
Hi,
I've done all of the above for reading multipacks etc.. and I followed your instructions exactly so not quite sure. I know what the package.json and gemfiles are. your .bundler had the ruby package so wasn't sure if anything was missing there ;).

Do you know if this still works for you if you deploy? Could something have changed in how Heroku does things?

My guess is something with the multipack isn't working. looks like the Apt buildpack is running fine, then it pulls down mosquitto buildpack and croaks.. 

I couldn't find a way to get a more verbose log from heroku though.

**Comment by rolandjitsu** [comment]
@prussiap I remember encountering the same issue, but I think I could not find a fix to it. I am unsure if anyone else tried it and it worked.

I think the issue was with installing mosquito. I haven't tried it in a year or so, but if I get some time on my hands I could try to make a quick project on heroku and see if it manages to install this buildpack and mosquito.

**Comment by prussiap** [comment]
@rolandjitsu that would be fantstic if you gave it a shot. I'd love to get my own broker up and going in the cloud ;) .. I'm still not sure if it's cause mosquitto failed or the multipack failed to install more then one..

**Comment by rolandjitsu** [comment]
@prussiap I have tried to make this work but I could not manage to do so. On the other hand, this buildpack would only install a binary and nothing more. If you want a fully functional MQTT client I would suggest using [CloudMQTT](https://devcenter.heroku.com/articles/cloudmqtt).

I will delete this repo since it is not working and I do not have the time to look into it furthermore. Sorry for misleading you.
